<a href="https://colab.research.google.com/github/pranavpatnaik1/introToPyTorch/blob/main/introToTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

Learning from learnpytorch.io

In [2]:
import torch
torch.__version__

'2.6.0+cu124'

In [4]:
# Scalars are "zero-dimension" vectors.

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim # number of dimensions

0

In [6]:
scalar.item # actual number from tensor

<function Tensor.item>

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

Note that the number of dimensions is merely the number of square brackets surrounding the vector. In this case, it's 1.

In [10]:
vector.shape

torch.Size([2])

Note that the *shape* of the vector is 2.

In [11]:
matrix = torch.tensor([[2,2],
                      [2,3]])

matrix

tensor([[2, 2],
        [2, 3]])

In [13]:
matrix.ndim

2

The number of dimensions this matrix has is 2 (note the number of brackets)

In [15]:
matrix.shape

torch.Size([2, 2])

The _shape_ of this matrix is 2 elements deep and 2 elements wide.

In [19]:
tensor = torch.tensor([[[2,2,3],
                       [3,4,5],
                       [5,6,7]]])

tensor

tensor([[[2, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [21]:
tensor.ndim # 3 dimensions; note the brackets

3

In [23]:
tensor.shape # 1 dim of 3x3

torch.Size([1, 3, 3])

In [26]:
zeroes = torch.zeros(size=(3,4))
zeroes, zeroes.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)